name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Digital Ocean 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -qq openssh-client

    - name: Add SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Connect to remote server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}  "cd ${{ secrets.WORK_DIR }} && git pull && cd ${{ secrets.CLIENT_DIR }}  && npm run build &&  exit"
    - name: cleanup
      run: rm -rf ~/.ssh
      
